export const PROPERTIES_LIST = [
  { key: "total_population", display: "Total population"},
  { key: "race_white", display: "white"},
  { key: "race_hispanic_latino", display: "hispanic and latino"},
  { key: "race_other", display: "other"},
  { key: "race_asian", display: "asian"},
  { key: "race_2_or_more", display: "2 or more"},
  { key: "race_black", display: "black"},
  { key: "race_indigenous", display: "indigenous"},
  { key: "foreign_born", display: "foreign born"},
  { key: "speaks_non_english_at_home", display: "speaks a language other than English at home"},
  { key: "identifies_as_speaking_english_less_well", display: "self identifies as speaking English less than very well"},
  { key: "median_age", display: "median age"},
  { key: "rent_as_percent", display: "rent as a percent of income"},
  { key: "median_gross_rent", display: "median gross rent"},
  { key: "median_home_value", display: "median home value"},
  { key: "poverty_level", display: "poverty level"},
  { key: "homeowners", display: "homeowners"},
  { key: "renters", display: "renters"},
  { key: "unemployment", display: "unemployment"},
  { key: "median_income", display: "median income"},
  { key: "high_school_grad", display: "high school grad or higher"},
  { key: "neighborhood_id", display: "id"},
  { key: "neighborhood_name", display: ""},
  { key: "notes", display: "notes"}
];